# Dependencies
auto: true
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty

# Setup
title: 写在边上
tagline: 'Never left without love, peace, and saying goodbye.'
description: "Astrian's blog"
url: http://mdblog.astrianfm.com
future: true
timezone: Asia/Beijing

author:
  name: 'Astrian'
  email: mingriqd@gmail.com

paginate: 5
